#!/bin/bash
echo "======================================"
echo "REPLIT FILE FIX INSTRUCTIONS"
echo "======================================"
echo ""
echo "1. Open the .replit file in your editor"
echo ""
echo "2. Find these lines (around line 34-56):"
echo "   DELETE FROM HERE:"
grep -n "\[\[ports\]\]" .replit | head -1
echo "   TO HERE:"
grep -n "\[userenv\]" .replit
echo ""
echo "3. DELETE all [[ports]] sections (lines 34-56)"
echo ""
echo "4. Your file should look like this after the deletion:"
echo "   Line 32: waitForPort = 5000"
echo "   Line 33: (blank line)"
echo "   Line 34: [userenv]"
echo "   Line 35: (blank line)"
echo "   Line 36: [userenv.shared]"
echo ""
echo "5. Save the file (Ctrl+S or Cmd+S)"
echo ""
echo "6. Click the 3-dot menu at top → 'Restart Repl'"
echo ""
echo "======================================"
echo "WHY: You have TWO ports trying to use port 80:"
cat .replit | grep -B1 "externalPort = 80"
echo "======================================"
